### ISSUE TITLE
Build wheels for public releases

### ISSUE THREAD

**Issue by Drache91** [python/mypy_extensions#14]
Hi, while installing mypy I stumbled upon an error while installing and it seems that `mypy-extensions` is causing this.

I try to install mypy (and thus mypy-extensions) within a fresh virtual environment from powershell on a Windows 10 (1903) machine. The error can be reproduced when just installing `mypy-extensions`.

- Python Version: 3.7.4
- pip version: 19.3

Other packages install just fine.

Here is what I've done to reproduce it:

```ps
PS F:\Programmierung\YTThingy> virtualenv venv
Using base prefix 'c:\\users\\username\\appdata\\local\\programs\\python\\python37'
New python executable in F:\Programmierung\YTThingy\venv\Scripts\python.exe
Installing setuptools, pip, wheel...
done.
PS F:\Programmierung\YTThingy> .\venv\Scripts\activate
(venv) PS F:\Programmierung\YTThingy> python -V
Python 3.7.4
(venv) PS F:\Programmierung\YTThingy> Get-Command pip
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     pip.exe                                            0.0.0.0    F:\Programmierung\YTThingy\venv/Script...


(venv) PS F:\Programmierung\YTThingy> Get-Command python
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     python.exe                                         3.7.415... F:\Programmierung\YTThingy\venv/Script...


(venv) PS F:\Programmierung\YTThingy> python -m pip --version
pip 19.3 from F:\Programmierung\YTThingy\venv\lib\site-packages\pip (python 3.7)
(venv) PS F:\Programmierung\YTThingy> python -m pip install mypy-extensions
Collecting mypy-extensions
  Using cached https://files.pythonhosted.org/packages/1e/2f/7bba47eb58f62a473387cd7658dedd0bedb4b0fa9d530bbbfa0a6d23034a/mypy_extensions-0.4.2.tar.gz
    ERROR: Error [WinError 87] Falscher Parameter while executing command python setup.py egg_info
ERROR: Could not install packages due to an EnvironmentError: [WinError 87] Falscher Parameter
(venv) PS F:\Programmierung\YTThingy> python -m pip --no-cache-dir install mypy-extensions
Collecting mypy-extensions
  Downloading https://files.pythonhosted.org/packages/1e/2f/7bba47eb58f62a473387cd7658dedd0bedb4b0fa9d530bbbfa0a6d23034a/mypy_extensions-0.4.2.tar.gz
    ERROR: Error [WinError 87] Falscher Parameter while executing command python setup.py egg_info
ERROR: Could not install packages due to an EnvironmentError: [WinError 87] Falscher Parameter
```
(It's a german System. "Falscher Parameter" == "wrong parameter")

**Comment by ethanhs** [comment]
Unfortunately, I am unable to repro this. Since our project just calls into setuptools, I think you'll have more luck reporting the issue there. If I had to guess it would be something like pip is duplicating the file descriptors for the setup process, which is failing (there have been various bugs reported about this, but none match your system or Python as far as I can tell.

Btw, as an action item for us, we should probably release wheels so people don't need to run `setup.py egg_info` as part of install.

**Comment by Drache91** [comment]
Oh well, thank you non the less :)

I suppose this can be considered closed now?

**Comment by ilevkivskyi** [comment]
Let's keep this open as a reminder to build wheels for the next release.

**Comment by msullivan** [comment]
I've uploaded a 0.4.2 wheel and released a 0.4.3 with a wheel. (0.4.3 was basically just to catch an update to the URL).

I've updated our internal playbook with directions for creating the wheel

Thanks!

**Comment by nicktimko** [comment]
I'm not sure how this was even possible; I thought PyPI blocked uploads of releases after you uploaded the source distribution for that version/package. Or maybe it was after you upload the binary release?...

In any event, please don't retro-release again, it causes some pain (#15)

**Comment by gvanrossum** [comment]
Why is this our fault and not a bug in pipenv? Please open an issue with pipenv.
