### ISSUE TITLE
0.4.2 resubmitted to pypi?

### ISSUE THREAD

**Issue by MichaelAquilina** [python/mypy_extensions#15]
`pipenv install` is currently failing for me because the hash for 0.4.2 has a different hash to what was found the first time it was locked with `pipenv lock`.

0.4.2 was released on 3rd October 2019

![2019-10-18_11-34-45](https://user-images.githubusercontent.com/2650040/67087693-52a0b700-f19b-11e9-8679-08076dd75a37.png)

However another wheel was uploaded yesterday on the 17th October 2019

![2019-10-18_11-39-54](https://user-images.githubusercontent.com/2650040/67088022-09049c00-f19c-11e9-9d84-74877cff7e9f.png)

Which happens to coincide with the release of 0.4.3

![2019-10-18_11-40-28](https://user-images.githubusercontent.com/2650040/67088052-1c176c00-f19c-11e9-9155-56198de0e7c0.png)

It seems like 0.4.2 was re-submitted (potentially with changes) and the hash has changed for that reason. The worst case scenario would be that the package was resubmitted with malicious changes. The simplest explanation would just be that it was simply re-uploaded with some changes by mistake. 

I cant be sure without confirmation here though :/

**Comment by ilevkivskyi** [comment]
We deliberately added a wheel that was previously missing, see https://github.com/python/mypy_extensions/issues/14#issuecomment-543390739

**Comment by MichaelAquilina** [comment]
This is probably breaking the builds for many pipenv users right now. 

Once something is released its probably best to not re-upload new artifacts to pypi? It's very hard to tell if something is a legitimate upload if it comes out of the blue.

**Comment by nicktimko** [comment]
My Pipenv is exploding now with 

```
...
n error occurred while installing mypy-extensions==0.4.2 --hash=sha256:a161e3b917053de87dbe469987e173e49fb454eca10ef28b48b384538cc11458! Will try again.                                                    
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 66/66 — 00:00:39                                                                                                                                                     
Installing initially failed dependencies…                                                                                                                                                                    
[pipenv.exceptions.InstallError]:   File "/home/nick/.pyenv/versions/3.7.2/envs/global3/lib/python3.7/site-packages/pipenv/core.py", line 2611, in do_sync                                                   
[pipenv.exceptions.InstallError]:       system=system,                                                                                                                                                       
[pipenv.exceptions.InstallError]:   File "/home/nick/.pyenv/versions/3.7.2/envs/global3/lib/python3.7/site-packages/pipenv/core.py", line 1253, in do_init                                                   
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,                                                                                                                                             
[pipenv.exceptions.InstallError]:   File "/home/nick/.pyenv/versions/3.7.2/envs/global3/lib/python3.7/site-packages/pipenv/core.py", line 859, in do_install_dependencies                                    
[pipenv.exceptions.InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs                                                                                             
[pipenv.exceptions.InstallError]:   File "/home/nick/.pyenv/versions/3.7.2/envs/global3/lib/python3.7/site-packages/pipenv/core.py", line 763, in batch_install                                              
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, not blocking, failed_deps_queue, retry=retry)                                                                                                  
[pipenv.exceptions.InstallError]:   File "/home/nick/.pyenv/versions/3.7.2/envs/global3/lib/python3.7/site-packages/pipenv/core.py", line 681, in _cleanup_procs                                             
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)                                                                                                           
[pipenv.exceptions.InstallError]: ['Looking in indexes: https://pypi.org/simple', 'Co
llecting mypy-extensions==0.4.2 (from -r /tmp/pipenv-awpxe0iz-requirements/pipenv-wpdqips1-requirement.txt (line 1))', '  Using cached https://files.pythonhosted.org/packages/55/aa/2df16f9c6215b10c472fd756
4b5f2c5644c13ab9c26d83b1c9373c11d97d/mypy_extensions-0.4.2-py2.py3-none-any.whl']                                                                                                                            
[pipenv.exceptions.InstallError]: ['THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package con
tents carefully; someone may have tampered with them.', '    mypy-extensions==0.4.2 from https://files.pythonhosted.org/packages/55/aa/2df16f9c6215b10c472fd7564b5f2c5644c13ab9c26d83b1c9373c11d97d/mypy_exte
nsions-0.4.2-py2.py3-none-any.whl#sha256=c77e34350c01523cd63b6dc30b36515107b2c3cbacc8392d51d33ea18d59f8f1 (from -r /tmp/pipenv-awpxe0iz-requirements/pipenv-wpdqips1-requirement.txt (line 1)):', '        Ex
pected sha256 a161e3b917053de87dbe469987e173e49fb454eca10ef28b48b384538cc11458', '             Got        c77e34350c01523cd63b6dc30b36515107b2c3cbacc8392d51d33ea18d59f8f1']                                 
ERROR: ERROR: Package installation failed...                                                                                                                                                                 
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/1 — 00:00:01  
```

Please be aware that editing releases you will potentially break builds. PyPI supports "post" as a version suffix, e.g. 0.4.2post1 which could be used for that sort of thing.

**Comment by MichaelAquilina** [comment]
Just to be clear, I got the exact same error message

**Comment by ilevkivskyi** [comment]
IMO this is a pipenv bug. What is wrong with uploading new artefacts? FYI, artefacts are always uploaded one by one, just with interval of seconds rather than days, but what this changes in principle?

**Comment by MichaelAquilina** [comment]
I would argue It breaks the ability for pipenv to reliably check hashes if you take that approach though. I dont think there is a mechanism which pipenv can "request" an artifact matching a specific hash (and I'm not sure it even should).

**Comment by nicktimko** [comment]
It could well be a pipenv bug (could be fixed in master, but last release is ~1 year old :roll_eyes: ), but I thought PyPI also locks down the version after some point. I thought I recall trying to upload a wheel I just built after the sdist, but PyPI (via Twine) was throwing errors at me saying no. I figured if you didn't upload them at the same time it would just fail?

**Comment by ethanhs** [comment]
>I dont think there is a mechanism which pipenv can "request" an artifact matching a specific hash.

pipenv ~could~ *should* store the URL it got the artifact from, as that should be static and safe. This seems to be much more correct. People upload later all the time, so I strongly feel pipenv should change here.

>I thought PyPI also locks down the version after some point

AFAIK, PyPi only restricts uploading an artifact with the same name.
