### ISSUE TITLE
Default Values for TypedDict

### ISSUE THREAD

**Issue by rmorshea** [python/mypy_extensions#17]
It would be nice if you could set default values for a `TypedDict`:

```python
class Coordinate(TypedDict):
    x: int = 0
    y: int = 0
    z: int = 0

# current behavior
assert Coordinate() == {}
# desired behavior
assert Coordinate() == {"x": 0, "y": 0, "z": 0}
```

**Comment by JukkaL** [comment]
Since `TypedDict` is included in Python 3.8, proposed changes should go through CPython issues.

**Comment by scharf** [comment]
Which issue tracker to use for that? And how to import `TypedDict` in Python 3.8?

**Comment by ilevkivskyi** [comment]
Use https://bugs.python.org
