### ISSUE TITLE
Mark repo as defunct?

### ISSUE THREAD

**Issue by mfarrugi** [python/mypy_extensions#19]
Looks like this has been superseded by https://github.com/python/typing/tree/master/typing_extensions

**Comment by gvanrossum** [comment]
We could archive the repo.

**Comment by gvanrossum** [comment]
Hm, this repo is still needed if you want to use some mypy-specific features, esp. `Arg`, `DefaultArg` etc. It is still [mentioned](https://mypy.readthedocs.io/en/stable/additional_features.html#extended-callable-types) in the mypy docs (albeit deprecated).
