### ISSUE TITLE
Make a release that supports Python 3.9

### ISSUE THREAD

**Issue by JukkaL** [python/mypy_extensions#21]

**Comment by hauntsaninja** [comment]
Just bumping this

**Comment by gvanrossum** [comment]
@JelleZijlstra, @hauntsaninja, @srittau -- do you want access for this project too?

**Comment by JelleZijlstra** [comment]
Sure. I'd have to spend some time looking into what needs to be done. This project doesn't feel as relevant any more now that things like TypedDict have been standardized.

**Comment by srittau** [comment]
I'm not a mypy maintainer (and have only a very limited understanding of its internals), so I don't think I should have access to this repository.

**Comment by gvanrossum** [comment]
Well it looks like I'm not even a repo owner here, so it's up to @JukkaL anyway to hand out permissions. (But I do have permissions for the PyPI project. :-)

**Comment by JukkaL** [comment]
Now we finally have a release that officially supports 3.9 to 3.11. Sorry for the slow response. 

I invited @hauntsaninja as a maintainer. @JelleZijlstra if you are still interested in getting access, I can add you to the PyPI project if you tell me your PyPI username.
