### ISSUE TITLE
test_typeddict_errors fails on python3.11

### ISSUE THREAD

**Issue by mweinelt** [python/mypy_extensions#24]
Heads up, we're seeing a test failure with python 3.11.0rc2 and mypy_extensions. Python 3.11 will be released in October.

```
======================================================================
FAIL: test_typeddict_errors (testextensions.TypedDictTests.test_typeddict_errors)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/tests/testextensions.py", line 91, in test_typeddict_errors
    with self.assertRaises(TypeError):
AssertionError: TypeError not raised

----------------------------------------------------------------------
Ran 7 tests in 0.003s

FAILED (failures=1)
```

**Comment by gvanrossum** [comment]
Ah, I was confused. I've confirmed your report on macOS. I didn't try earlier versions of Python 3.11, but the tests pass with 3.10.

Do you have time to debug this further? I'm guessing something in the stdlib typing.py module changed, but I don't have time to investigate further.

**Comment by mweinelt** [comment]
Works on 3.11.0a6, broke on 3.11.0a7. I'm not too familiar with the cpython codebase and I don't have a setup ready to bisect this any further.

**Comment by gvanrossum** [comment]
@JelleZijlstra -- what could have broken this? It seems to be this code at L91-92 that no longer raises `TypeError`:
```py
        with self.assertRaises(TypeError):
            TypedDict('Hi', x=1)
```
A lot of stuff went in between a6 and a7, including PEP 646, and a bunch of refactoring by Serhiy.

**Comment by JelleZijlstra** [comment]
I think that's because of 870b22b9c442d035190d2b8fb82256cd9a03da48 (python/cpython#31151).

**Comment by gvanrossum** [comment]
So the test should just be fixed.
