### ISSUE TITLE
Convert CI from Travis to GitHub Actions?

### ISSUE THREAD

**Issue by bluetech** [python/mypy_extensions#39]
The project has a .travis.yml file, but it seems non-functional -- at least it doesn't look like it's triggered in CI. Would you be interested in replacing it with GitHub Actions? I can send a PR doing this if so.

**Comment by JelleZijlstra** [comment]
Yes, we should do that. This project hasn't seen much activity, but would be good to keep it maintained.

**Comment by bluetech** [comment]
Also, it seems like pre-commit.ci is configured for this repo, but a pre-commit.yml file is not available so it fails. The CI runs tox lint, but if you prefer pre-commit I can add a pre-commit file to the repo. Otherwise I suggest turning pre-commit.ci off for this repo.

**Comment by JelleZijlstra** [comment]
I don't think I have the permissions to turn off pre-commit. Jukka does but I'd prefer not to bother him, so we might as well add a pre-commit config file.
