### ISSUE TITLE
Deprecate `mypy_extensions.TypedDict`?

### ISSUE THREAD

**Issue by AlexWaygood** [python/mypy_extensions#46]
`mypy_extensions.TypedDict` is problematic for several reasons:

- `mypy_extensions.TypedDict` is missing quite a few features that have been added to `typing.TypedDict` at runtime (and have been backported to `typing_extensions.TypedDict`).
- I think the existence of both `mypy_extensions.TypedDict` and `typing_extensions.TypedDict` has the potential to be pretty confusing for users.
- It's quite annoying and error-prone that at typeshed, we have to remember to keep `typing._TypedDict`, `typing_extensions._TypedDict` and `mypy_extensions._TypedDict` all in sync. Unfortunately, we can't put them all in `_typeshed` and have all three modules import `_TypedDict` from `_typeshed`, as the three classes all have slightly subtle differences. (E.g. `mypy_extensions._TypedDict` doesn't have the `__required_keys__` and `__optional_keys__` ClassVars that both `typing._TypedDict` and `typing_extensions._TypedDict` have.)
- Mypy now maintains its own copy of the `mypy-extensions` stubs anyway, so its stubs for `mypy_extensions` are no longer automatically updated with each typeshed sync. That means that even if we update the stubs for `mypy_extensions.TypedDict` in typeshed (as we did in https://github.com/python/typeshed/pull/10565), those updates are no longer of any benefit to mypy users unless mypy maintainers remember to copy across the changes to their forked version of the `mypy_extensions` stubs.

I propose that we deprecate `mypy_extensions.TypedDict`, and steer people towards `typing_extensions.TypedDict` instead: it's up-to-date with the features on `typing.TypedDict`, it's much more comprehensively tested, and it has up-to-date stubs.

Thoughts?

**Comment by JelleZijlstra** [comment]
Agree, there's no need for mypy_extensions.TypedDict any more. As an implementation strategy, we can:
* Raise a runtime DeprecationWarning when a new `mypy_extensions.TypedDict` class is created
* Have mypy show a warning whenever `mypy_extensions.TypedDict` is used

**Comment by AlexWaygood** [comment]
I'm taking a look at the runtime side of things. One issue: it seems we'd really need `stacklevel=3` if you're constructing a `TypedDict` class like this:

```py
Foo = TypedDict('Foo', {'x': int})
```

...But you'd need `stacklevel=2` if you're constructing a `TypedDict` like this:

```py
class Bar(TypedDict):
    x: int
```

I'm not sure if there's a way to distinguish between the two, if we emit the `DeprecationWarning` in `_TypedDictMeta.__new__`

**Comment by AlexWaygood** [comment]
> I'm not sure if there's a way to distinguish between the two, if we emit the `DeprecationWarning` in `_TypedDictMeta.__new__`

Hmm, I think I have a solution
