### ISSUE TITLE
Expose required/non-required keys for mixed TypedDict or TypedDict base class, in runtime

### ISSUE THREAD

**Issue by shamrin** [python/mypy_extensions#7]
MyPy documentation mentions it's possible to mix required and non-required items in TypedDict:

```python
class MovieBase(TypedDict):
    name: str
    year: int

class Movie(MovieBase, total=False):
    based_on: str
```

https://mypy.readthedocs.io/en/latest/more_types.html#mixing-required-and-non-required-items

Unfortunately, I couldn't find how to see which of `Movie` keys are required, in runtime. I can only get a list of all fields (`__annotations__`) and the fact `Movie` is non-total (`__total__`).

```python
>>> from mypy_extensions import TypedDict
>>> class MovieBase(TypedDict):
...     name: str
...     year: int
... 
>>> class Movie(MovieBase, total=False):
...     based_on: str
... 
>>> Movie.__annotations__
{'based_on': <class 'str'>, 'name': <class 'str'>, 'year': <class 'int'>}
>>> Movie.__total__
False
```

Alternatively I could poke into original base classes to find out which keys are required, but I it doesn't work:

```python
>>> Movie.__bases__
(<class 'dict'>,)
```

I'm trying to write a function that checks if data matches its `TypedDict` type, in runtime. I can't implement it without knowing which keys are required.

**Comment by shamrin** [comment]
Probably related:

* [typing_inspect library issue #19]( https://github.com/ilevkivskyi/typing_inspect/issues/19)
* [Reddit comment thread](https://www.reddit.com/r/Python/comments/8hmjq9/the_other_great_benefit_of_python_type_annotations/dylexje/)

**Comment by ilevkivskyi** [comment]
On one hand, this is pretty niche, but on the other hand, if you have a simple addition to the private `TypedDict` API that would allow supporting this in `typing_inspect`, then we may accept the PRs (here and then in `typing_inspect`).

**Comment by JelleZijlstra** [comment]
This is fixed in `typing.TypedDict` and `typing_extensions.TypedDict`. There is really no reason to still use `mypy_extensions.TypedDict`.

https://docs.python.org/3.10/library/typing.html#typing.TypedDict.__required_keys__
